### ISSUE TITLE
我想自定义char_map.json

### ISSUE THREAD

**Issue by Giggledefy** [bai-shang/OCR_TF_CRNN_CTC#10]
如题，比如说我就想要识别数字和BDFGHKSWXYZ这几个大写字母，应该如何编辑char_map.json？
我尝试改成`{"B":0,"D":1,"F":2…………"9":20}`，结果训练报错了

**Comment by austingg** [comment]
@Giggledefy 你应该提供更详细的错误信息， 报错了， 这个太笼统了

**Comment by bai-shang** [comment]
关于如何提问的建议：https://zhuanlan.zhihu.com/p/20752519
