### ISSUE TITLE
evaluation精度和inference精度不同

### ISSUE THREAD

**Issue by boris-lb** [bai-shang/OCR_TF_CRNN_CTC#14]
训练完成后，eval_crnn_ctc精度正常，但是使用inference_crnn_ctc跑测试集，预测值全为7，我是四位的验证码数据，有遇到类似问题的么？

**Comment by bai-shang** [comment]
没有遇到此类问题。
eval_crnn_ctc和inference_crnn_ctc在测试阶段使用代码一致，只不过eval多了与GT对比而已。
