### ISSUE TITLE
训练问题，求助！

### ISSUE THREAD

**Issue by msxfXF** [bai-shang/OCR_TF_CRNN_CTC#16]
用网盘上的模型，可以正确预测出英文字母。

用自己的数据进行识别数字的训练，训练的时 acc 和loss 都很理想。
但是使用自己模型预测时，无论输入什么图片，预测结果均为 838383838383838383838

这可能是什么情况？
![image](https://user-images.githubusercontent.com/38368353/58364979-a7dbe380-7eef-11e9-813f-13114e901ccd.png)
![image](https://user-images.githubusercontent.com/38368353/58364982-bde9a400-7eef-11e9-8236-ea299cf8c7b6.png)

**Comment by bai-shang** [comment]
这step1500就收敛了，感觉不是很合理。
1. 在repo中原始的图片能收敛么？还是只在你自己数据集存在这个问题？
2. step1500就完全过拟合了，不太对。能贴出几张你训练集的图么？

**Comment by msxfXF** [comment]
方便留个QQ或者联系方式吗？

**Comment by msxfXF** [comment]
在inference_crnn_ctc读取模型时，tf.train.latest_checkpoint 可以正常返回模型的路径。
但是 saver.restore 后，输出saver._filename 返回null。
这正常吗？

**Comment by Li-Xiao-Yu** [comment]
@msxfXF 你解决这个问题了吗？
