### ISSUE TITLE
Error when I training !

### ISSUE THREAD

**Issue by ThorPham** [bai-shang/OCR_TF_CRNN_CTC#2]
Can you help me fix error ?  . Thank so much.
when i create file tf.record it has error:
 File "create_synth90k_tfrecord.py", line 49, in _bytes_feature
    value = value.encode('utf-8') # convert string object to bytes
AttributeError: 'bytes' object has no attribute 'encode'

-  I change a little your code : str(image_buffer.tostring()) and it work but when i run model have error : 

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_batch/padding_fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: batch = QueueDequeueManyV2[_class=["loc:@batch/control_dependency_4"], component_types=[DT_FLOAT, DT_INT64, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/padding_fifo_queue, batch/n)]]

**Comment by bai-shang** [comment]
What's your python version? py2.7 py3.5 or py3.6?

**Comment by ThorPham** [comment]
I using python 3.5 and tensorflow 1.7

**Comment by bai-shang** [comment]
Please use the new code. This problom has been fixed now.
