### ISSUE TITLE
代码里ctc_beam_search_decoder()里的merge_repeated应该设置为False吧

### ISSUE THREAD

**Issue by MTaoYue** [bai-shang/OCR_TF_CRNN_CTC#5]
inference_crnn_ctc.py/90

**Comment by bai-shang** [comment]
你可以自己试试区别。
我在实际工程中使用的是warp_ctc的cpp代码，所以对tf ctc api具体实现方式我并不是很清楚。

**Comment by MTaoYue** [comment]
谢谢@bai-shang 回复，感谢作者知乎的分享！！贴下注释
`A B B * B * B` (where '*' is the blank label), the return value is:
    * `A B` if `merge_repeated = True`.
    * `A B B B` if `merge_repeated = False`.

**Comment by zfzf1990** [comment]
感谢分享
